### ISSUE TITLE
Edição 6 - Agosto de 2016

### ISSUE THREAD

**Issue by RafaelFunchal** [wpbrasil/correiowp#1]
Olá, galera!

Sim, após 1 ano sem nenhuma nova edição, estamos de volta!

Essa é a primeira issue para o CorreioWP.

Comentem com suas sugestões, uma sugestão por comentário.

**Comment by theandersonn** [comment]
Sugestões de Eventos

**WordCamp**

---

WordCamp Fortaleza 2016
https://fortaleza.wordcamp.org/2016/
13 e 14 de agosto de 2016

**Meetups**

---

10º Meetup WordPress Fortaleza
27 de agosto de 2016
http://www.meetup.com/pt-BR/wpfortaleza/events/231900382/

Meetup WordPress Curitiba 
27 de agosto de 2016
http://www.meetup.com/pt-BR/wpcuritiba/events/232806785/

**Comment by allysonsouza** [comment]
Como funciona as sugestões? O que pode conter no CorreioWP? Era pro CorreioWP que tinha uma galera sugerindo plugins no #slack?

Se for, tenho uma sugestão de plugin bem legal, de pesquisa de imagens para utilização em posts, utiliza o pixabay.com e o flickr, buscando imagens nestes bancos que podem ser inseridas no conteúdo ou diretamente definidas como imagens destacadas: https://wordpress.org/plugins/wp-inject/

**Comment by RafaelFunchal** [comment]
Acho que perdi essa conversa lá no Slack, @allysonsouza , mas sim, o CorreioWP também tem sugestão de plugins.

Caso queira ver o que já falamos nas edições passadas (a última foi há mais de 1 ano), aqui está o histórico: http://correiowp.com/categoria/edicoes/

**Comment by theandersonn** [comment]
**Tutorial:** Lista de Espera WooCommerce para Produtos Fora de Estoque
**Descrição:** Explicação de como criar uma lista de espera para lojas virtuais utilizando o plugin 'YITH WooCommerce Waiting List'.
**Link:** https://www.canalwp.com/woocommerce/lista-espera-woocommerce-produtos-fora-estoque/

**Comment by theandersonn** [comment]
**Tutorial:** Migração do WordPress: Como migrar do wordpress.com para wordpress.org
**Descrição:** Explicação do wordpress.com para wordpress.org e os passos para realizar a migração.
**Link:** https://www.yogh.com.br/blog/como-migrar-do-wordpress-com-para-wordpress-org/

**Comment by RafaelFunchal** [comment]
**Tutorial**: Configurando um VPS com EasyEngine
**Descrição**: Passos para instalar o EasyEngine em um VPS e criar uma nova instalação do WordPress. 
**Link**: http://www.rafaelfunchal.com.br/blog/tutoriais/configurando-um-vps-com-easyengine/

**Comment by RafaelFunchal** [comment]
**Dica**: Faça parte da comunidade
**Descrição**: Participe da comunidade WordPress Brasil no Slack.
**Link**: http://slack-wpbrasil.herokuapp.com/

**Comment by theandersonn** [comment]
**19º WordPress Meetup RJ**
**Descrição:** Slides e vídeo da palestra "Material Design – do smartphone ao desktop".
**Link:** http://wprio.org/meetups/19o-wordpress-meetup-rj

**Comment by RafaelFunchal** [comment]
@rudwolf , eu estava pensando em mandar o email essa sexta. O que você acha?

**Comment by rudwolf** [comment]
Pra mim perfeito. Só fica então o limite de envio de sugestões definido como quarta feira até o fim do dia. Pra podemos lançar isto na sexta já que temos que fazer a curadoria de artigos.

**Comment by valeriosouza** [comment]
Ja foi enviado a lista de segurança do Funchal?

**Comment by theandersonn** [comment]
@valeriosouza Saiu na [edição 5](http://us3.campaign-archive1.com/?u=f86cb49d090859ddb2b423aaf&id=6f3b60c1c6)

**Comment by theandersonn** [comment]
Slides das palestras do WordCamp BH 2016
**Link:** https://2016.belohorizonte.wordcamp.org/07/26/arquivos-e-apresentacoes/

**Comment by rudwolf** [comment]
O que vai mudar no WordPress 4.6
**Link:** http://krakenagencia.com.br/o-que-vai-mudar-no-wordpress-4-6/

**Comment by theandersonn** [comment]
Sugestões de Eventos

WordPress POA Meetup
30 de Agosto de 2016
http://www.meetup.com/pt-BR/wp-poa/events/232338174/

**Comment by rudwolf** [comment]
Aviso: Novos links e sugestões serão aceitas só até o fim do dia (zero hora de 04/08).

Amanhã (04/08) será feita a curadoria, para participar clique no smile no cantu superior direto de cada sugestão e vote com +1. Os artigos mais votados vão entrar na próxima edição. Não havendo voto suficiente ou empate entre artigos, decidiremos eu e @RafaelFunchal os artigos que estarão na próxima edição que será enviada dia 05/08.

PS: Como por enquanto não tem tantos artigos assim, então bem provável que todas as sugestões vão estar na próxima edição.

Abraço!

**Comment by valeriosouza** [comment]
Vagas para profissionais WordPress

https://hangarwp.com/

**Comment by RafaelFunchal** [comment]
Newsletter disparada!
