### ISSUE TITLE
Edição 7 - Setembro de 2016

### ISSUE THREAD

**Issue by RafaelFunchal** [wpbrasil/correiowp#2]
Criando uma nova issue para receber as sugestões da próxima edição.

**Comment by theandersonn** [comment]
**Título:** Trabalhando com shortcodes no WordPress
**Descrição:** Passos para a criação de shortcodes no WordPress e tratamento para que o código não quebre o tema.
**Link:** http://www.fellyph.com.br/blog/wordpress-2/criando-shortcodes-no-wordpress/

**Comment by theandersonn** [comment]
**Título:** WordCamp Rio de Janeiro 2016
**Descrição:** A edição carioca acontecerá dia 24 de setembro na Universidade Veiga de Almeida, Campus Tijuca; haverá palestras, atividades pararelas e muito networking com profissionais, estudantes e apaixonados por WordPress.
**Link:** https://2016.riodejaneiro.wordcamp.org/

**Comment by theandersonn** [comment]
**Título:** 33 Recursos gratuitos para WooCommerce
**Descrição:** Seleção com vários plugins para integração com o WooCommerce.
**Link:** http://academiawordpress.com.br/recursos-gratuitos-para-woocommerce/

**Comment by theandersonn** [comment]
**Título:** Aprenda mais sobre WordPress e impulsione sua carreira!
**Descrição:** https://2016.riodejaneiro.wordcamp.org/aprender-wordpress-carreira/
**Link:** Aprender WordPress é muito mais do que aprender código. Esse post vai te ajudar a ter uma ideia melhor do que é WordPress e mostrar como aprender mais sobre essa ferramenta pode impulsionar sua carreira.

**Comment by theandersonn** [comment]
**Agenda de eventos**

**11º Meetup WordPress Fortaleza**
**Data:** 20 de Setembro
**Descrição:** Primeiro meetup depois do WordCamp Fortaleza! Essa é uma ótima oportunidade de nos conhecermos melhor e também de consolidarmos conhecimento e networking.
http://www.meetup.com/pt-BR/wpfortaleza/events/233598570/

**Comment by theandersonn** [comment]
**Agenda de eventos**

**Meetup WordPress Salvador**
**Data:** 8 de Setembro
**Descrição:**A volta dos Meetup sobre WordPress, 
http://www.meetup.com/pt-BR/wp-salvador/events/233793539/?eventId=233793539

**Comment by rudwolf** [comment]
**WordPress mobile é o que você precisa. Mobilize-se com WordPress**
**Descrição:** WordPress Mobile. Por que você ainda não está aproveitando da explosão dos acessos móveis no Brasil? Mobilize-se com o WordPress.
https://blog.apiki.com/2016/08/24/mobilize-se-com-wordpress/

**Comment by rudwolf** [comment]
**Pepper, a versão 4.6 do WordPress já está disponível!**
**Descrição:** Em homenagem ao saxofonista Pepper Adams, a nova versão do WordPress já está disponível para download, já sabe o que mudou? Não? Confira aqui!
http://krakenagencia.com.br/pepper-versao-4-6-do-wordpress-ja-esta-disponivel/

**Comment by rudwolf** [comment]
Newsletter Enviada!
