### ISSUE TITLE
Edição 8 - Outubro de 2016

### ISSUE THREAD

**Issue by rudwolf** [wpbrasil/correiowp#3]
Criando uma nova issue para receber as sugestões da próxima edição.

**Comment by donini** [comment]
**Título:** Automação de desenvolvimento de projetos Wordpress
**Descrição:** Facilitar o desenvolvimento e melhorar a qualidade do projeto publicado se tornou obrigatório. Com este framework é possível realizar o download da última versão, configurar, instalar e atualizar o core do WP, criar um scaffold de um tema, compilar de sass, js, gerar sprites de imagens e watch (livre reload).
**Link:** https://github.com/donini/wordpress-automation

**Comment by HenriqueSilverio** [comment]
**Título:** Internacionalização de JavaScript no WordPress
**Descrição:** Aprenda na prática, como internacionalizar código JavaScript em seus plugins e temas.
**Link:** http://henriquesilverio.github.io/wordpress/internacionalizacao-de-javascript-no-wordpress

**Comment by RafaelFunchal** [comment]
@donini , dê uma olhada no seu projeto. Está cheio de WordPress com P minúsculo lá e na sua sugestão aqui também.

**Comment by donini** [comment]
Fala @RafaelFunchal, realizei os ajustes, obrigado pelo toque.

**Comment by rudwolf** [comment]
**Título:** WordPress 4.7 trará um novo tema padrão
**Descrição:** A desenvolvedora chefe da nova versão do WordPress 4.7 Helen Hou-Sandi apresentou um projeto para novo tema padrão que estará disponível na próxima versão, conheça o Thenty Seventeen.
**Link:** http://meucanto.net/wordpress-4-7-novo-tema/

**Comment by claudiosanches** [comment]
**Título:** Ações em massa personalizadas no WordPress 4.7
**Descrição:** O WordPress 4.7 vai permitir que os desenvolvedores criem ações em massa personalizadas gerenciar as listas de conteúdo do painel administrativo.
**Link:** https://wpbrasil.org/2016/10/05/acoes-em-massa-personalizadas/

**Comment by RafaelFunchal** [comment]
Fecharemos as sugestões na próxima quarta-feira, 19/10.

Então enviem suas dicas logo :-)

**Comment by RafaelFunchal** [comment]
**Título:** WordCamp São Paulo
**Descrição:** Inscreva-se no site para saber todas as novidades do WordCamp São Paulo que acontecerá em Dezembro.
**Link:** https://2016.saopaulo.wordcamp.org/

**Comment by rudwolf** [comment]
**Título:** Como não pedir ajuda na comunidade WordPress
**Descrição:** Descubra algumas maneiras de como NÃO pedir ajuda em fóruns e grupos.
**Link:** [http://www.rafaelfunchal.com.br/blog/como-nao-pedir-ajuda-na-comunidade-wordpress/](http://www.rafaelfunchal.com.br/blog/como-nao-pedir-ajuda-na-comunidade-wordpress/)

**Comment by rudwolf** [comment]
**Título:** Apiki lança whitepaper sobre SSL e WordPress
**Descrição:** A Apiki lançou recentemente o whitepaper gratuito “Tudo o que você precisa saber sobre SSL e WordPress”. Trata-se do segundo passo da iniciativa lançada em setembro pela empresa.
**Link:** [http://imasters.com.br/noticia/apiki-lanca-whitepaper-sobre-ssl-e-wordpress/](http://imasters.com.br/noticia/apiki-lanca-whitepaper-sobre-ssl-e-wordpress/)

**Comment by RafaelFunchal** [comment]
Se tem que informar seus dados pessoais para fazer download desse whitepaper, ele não é gratuito.

👎 para esse último aí

**Comment by rudwolf** [comment]
Este não vai entrar, não só por este motivo, mas por outros de um papo meu com o @claudiosanches que me deu um alerta mais brando sobre a empresa relacionada ao artigo (Apiki)
